#scp -pr . root@103.124.93.29:/root/

version: '3.8'
services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shopappnodejs
    ports:
      - 3308:3306
    #volumes:
    #- ./sql/shopapp.sql:/docker-entrypoint-initdb.d/init-script.sql

  phpmyadmin8-container:
    #intel host
    image: phpmyadmin/phpmyadmin
    #mac m1 host
    #image: arm64v8/phpmyadmin
    container_name: phpmyadmin8-container
    restart: always
    depends_on:
      - mysql8-container
    ports:
      - '8100:80' #port mapping
    environment:
      PMA_HOST: mysql8-container #phpMyAdmin Host, PMA = PHP My Amin

#docker-compose -f ./deployment.yaml rm -s -f mysql8-container // xóa
#docker-compose -f ./deployment.yaml up -d mysql8-container // tạo mới

#docker-compose -f ./deployment.yaml rm -s -f phpmyadmin8-container
#docker-compose -f ./deployment.yaml up -d phpmyadmin8-container

networks:
  shopapp-network:
    name: shopapp-network
    driver: bridge
